apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    api.kmontocam.com: "true"
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      real_ip_header CF-Connecting-IP;
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://kmontocam.com, https://www.kmontocam.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: |
      "Access-Control-Allow-Headers, Authorization, Content-Type, Cookie, HX-Boosted, HX-Current-URL, HX-History-Restore-Request, HX-Prompt, HX-Request, HX-Target, HX-Trigger-Name, HX-Trigger"
    nginx.ingress.kubernetes.io/cors-expose-headers: |
      "HX-Location, HX-Push-Url, HX-Redirect, HX-Refresh, HX-Replace-Url, HX-Reswap, HX-Retarget, HX-Reselect, HX-Trigger, HX-Trigger-After-Settle, HX-Trigger-After-Swap"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true" # allow cookies
    nginx.ingress.kubernetes.io/cors-max-age: "3600"
  name: kmontocam-backend
  namespace: kmontocam
spec:
  ingressClassName: nginx
  rules:
    - host: api.kmontocam.com
      http:
        paths:
          - path: /home/v1(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: kmontocam-backend
                port:
                  number: 80
